-- MySQL Script generated by MySQL Workbench
-- Tue Oct  9 17:15:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema beerify
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema beerify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `beerify` DEFAULT CHARACTER SET utf8 ;
USE `beerify` ;

-- -----------------------------------------------------
-- Table `beerify`.`prodotti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerify`.`prodotti` ;

CREATE TABLE IF NOT EXISTS `beerify`.`prodotti` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NULL,
  `descrizione` VARCHAR(400) NULL,
  `quantità` INT NULL,
  `prezzo` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cod_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerify`.`Indirizzi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerify`.`Indirizzi` ;

CREATE TABLE IF NOT EXISTS `beerify`.`Indirizzi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stato` VARCHAR(45) NULL,
  `città` VARCHAR(45) NULL,
  `via` VARCHAR(45) NULL,
  `cap` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerify`.`utenti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerify`.`utenti` ;

CREATE TABLE IF NOT EXISTS `beerify`.`utenti` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `congome` VARCHAR(45) NOT NULL,
  `ruolo` VARCHAR(10) NOT NULL,
  `Indirizzi_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Indirizzi_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_utenti_Indirizzi1_idx` (`Indirizzi_id` ASC),
  CONSTRAINT `fk_utenti_Indirizzi1`
    FOREIGN KEY (`Indirizzi_id`)
    REFERENCES `beerify`.`Indirizzi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerify`.`prodotti_in_evidenza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerify`.`prodotti_in_evidenza` ;

CREATE TABLE IF NOT EXISTS `beerify`.`prodotti_in_evidenza` (
  `id` INT NOT NULL,
  `data` VARCHAR(45) NULL,
  `prodotti_id` INT NOT NULL,
  PRIMARY KEY (`id`, `prodotti_id`),
  INDEX `fk_prodotti_in_evidenza_prodotti1_idx` (`prodotti_id` ASC),
  CONSTRAINT `fk_prodotti_in_evidenza_prodotti1`
    FOREIGN KEY (`prodotti_id`)
    REFERENCES `beerify`.`prodotti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerify`.`immagini_prodotti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerify`.`immagini_prodotti` ;

CREATE TABLE IF NOT EXISTS `beerify`.`immagini_prodotti` (
  `id` INT NOT NULL,
  `immagine` VARCHAR(60) NULL,
  `prodotti_id` INT NOT NULL,
  PRIMARY KEY (`id`, `prodotti_id`),
  INDEX `fk_immagini_prodotti_prodotti1_idx` (`prodotti_id` ASC),
  CONSTRAINT `fk_immagini_prodotti_prodotti1`
    FOREIGN KEY (`prodotti_id`)
    REFERENCES `beerify`.`prodotti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerify`.`recensioni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerify`.`recensioni` ;

CREATE TABLE IF NOT EXISTS `beerify`.`recensioni` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `testo` VARCHAR(300) NULL,
  `valutazione` INT NULL,
  `data` DATE NULL,
  `prodotti_id` INT NOT NULL,
  PRIMARY KEY (`id`, `prodotti_id`),
  INDEX `fk_recensioni_prodotti1_idx` (`prodotti_id` ASC),
  CONSTRAINT `fk_recensioni_prodotti1`
    FOREIGN KEY (`prodotti_id`)
    REFERENCES `beerify`.`prodotti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerify`.`carrello`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerify`.`carrello` ;

CREATE TABLE IF NOT EXISTS `beerify`.`carrello` (
  `id` INT NOT NULL,
  `prodotti_id` INT NOT NULL,
  `utenti_id` INT NOT NULL,
  PRIMARY KEY (`id`, `prodotti_id`, `utenti_id`),
  INDEX `fk_carrello_prodotti1_idx` (`prodotti_id` ASC),
  INDEX `fk_carrello_utenti1_idx` (`utenti_id` ASC),
  CONSTRAINT `fk_carrello_prodotti1`
    FOREIGN KEY (`prodotti_id`)
    REFERENCES `beerify`.`prodotti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrello_utenti1`
    FOREIGN KEY (`utenti_id`)
    REFERENCES `beerify`.`utenti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerify`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerify`.`tag` ;

CREATE TABLE IF NOT EXISTS `beerify`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerify`.`ordini`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerify`.`ordini` ;

CREATE TABLE IF NOT EXISTS `beerify`.`ordini` (
  `id` INT NOT NULL,
  `data` DATE NULL,
  `quantità` VARCHAR(45) NULL,
  `Indirizzi_id` INT NOT NULL,
  `carrello_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Indirizzi_id`, `carrello_id`),
  INDEX `fk_ordini_Indirizzi1_idx` (`Indirizzi_id` ASC),
  INDEX `fk_ordini_carrello1_idx` (`carrello_id` ASC),
  CONSTRAINT `fk_ordini_Indirizzi1`
    FOREIGN KEY (`Indirizzi_id`)
    REFERENCES `beerify`.`Indirizzi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordini_carrello1`
    FOREIGN KEY (`carrello_id`)
    REFERENCES `beerify`.`carrello` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerify`.`password_dimenticata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerify`.`password_dimenticata` ;

CREATE TABLE IF NOT EXISTS `beerify`.`password_dimenticata` (
  `id` INT NOT NULL,
  `token` VARCHAR(45) NULL,
  `data_scadenza` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerify`.`offerte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerify`.`offerte` ;

CREATE TABLE IF NOT EXISTS `beerify`.`offerte` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `prodotti_id` INT NOT NULL,
  PRIMARY KEY (`id`, `prodotti_id`),
  INDEX `fk_offerte_prodotti1_idx` (`prodotti_id` ASC),
  CONSTRAINT `fk_offerte_prodotti1`
    FOREIGN KEY (`prodotti_id`)
    REFERENCES `beerify`.`prodotti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerify`.`azienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerify`.`azienda` ;

CREATE TABLE IF NOT EXISTS `beerify`.`azienda` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NULL,
  `descrizione` VARCHAR(300) NULL,
  `social1` VARCHAR(100) NULL,
  `social2` VARCHAR(100) NULL,
  `social3` VARCHAR(100) NULL,
  `Indirizzi_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Indirizzi_id`),
  INDEX `fk_azienda_dettagli_Indirizzi1_idx` (`Indirizzi_id` ASC),
  CONSTRAINT `fk_azienda_dettagli_Indirizzi1`
    FOREIGN KEY (`Indirizzi_id`)
    REFERENCES `beerify`.`Indirizzi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerify`.`tag_prodotti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerify`.`tag_prodotti` ;

CREATE TABLE IF NOT EXISTS `beerify`.`tag_prodotti` (
  `tag_id` INT NOT NULL,
  `prodotti_id` INT NOT NULL,
  PRIMARY KEY (`tag_id`, `prodotti_id`),
  INDEX `fk_tag_has_prodotti_prodotti1_idx` (`prodotti_id` ASC),
  INDEX `fk_tag_has_prodotti_tag1_idx` (`tag_id` ASC),
  CONSTRAINT `fk_tag_has_prodotti_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `beerify`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tag_has_prodotti_prodotti1`
    FOREIGN KEY (`prodotti_id`)
    REFERENCES `beerify`.`prodotti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerify`.`immagini_utente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerify`.`immagini_utente` ;

CREATE TABLE IF NOT EXISTS `beerify`.`immagini_utente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `immagine` VARCHAR(60) NULL,
  `utenti_id` INT NOT NULL,
  PRIMARY KEY (`id`, `utenti_id`),
  INDEX `fk_immagini_utente_utenti1_idx` (`utenti_id` ASC),
  CONSTRAINT `fk_immagini_utente_utenti1`
    FOREIGN KEY (`utenti_id`)
    REFERENCES `beerify`.`utenti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerify`.`spedizioni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerify`.`spedizioni` ;

CREATE TABLE IF NOT EXISTS `beerify`.`spedizioni` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cod_tracking` VARCHAR(45) NULL,
  `nome_destinatario` VARCHAR(120) NULL,
  `utenti_id` INT NOT NULL,
  PRIMARY KEY (`id`, `utenti_id`),
  INDEX `fk_spedizioni_utenti1_idx` (`utenti_id` ASC),
  CONSTRAINT `fk_spedizioni_utenti1`
    FOREIGN KEY (`utenti_id`)
    REFERENCES `beerify`.`utenti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerify`.`preferiti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerify`.`preferiti` ;

CREATE TABLE IF NOT EXISTS `beerify`.`preferiti` (
  `utenti_id` INT NOT NULL,
  `prodotti_id` INT NOT NULL,
  `id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`utenti_id`, `prodotti_id`, `id`),
  INDEX `fk_utenti_has_prodotti_prodotti1_idx` (`prodotti_id` ASC),
  INDEX `fk_utenti_has_prodotti_utenti1_idx` (`utenti_id` ASC),
  CONSTRAINT `fk_utenti_has_prodotti_utenti1`
    FOREIGN KEY (`utenti_id`)
    REFERENCES `beerify`.`utenti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utenti_has_prodotti_prodotti1`
    FOREIGN KEY (`prodotti_id`)
    REFERENCES `beerify`.`prodotti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerify`.`news_letter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerify`.`news_letter` ;

CREATE TABLE IF NOT EXISTS `beerify`.`news_letter` (
  `id` INT NOT NULL,
  `email` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerify`.`richieste_reso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerify`.`richieste_reso` ;

CREATE TABLE IF NOT EXISTS `beerify`.`richieste_reso` (
  `utenti_id` INT NOT NULL,
  `prodotti_id` INT NOT NULL,
  `id` INT NOT NULL,
  `motivazione` VARCHAR(200) NULL,
  `approvata` TINYINT NULL,
  PRIMARY KEY (`utenti_id`, `prodotti_id`, `id`),
  INDEX `fk_utenti_has_prodotti_prodotti2_idx` (`prodotti_id` ASC),
  INDEX `fk_utenti_has_prodotti_utenti2_idx` (`utenti_id` ASC),
  CONSTRAINT `fk_utenti_has_prodotti_utenti2`
    FOREIGN KEY (`utenti_id`)
    REFERENCES `beerify`.`utenti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utenti_has_prodotti_prodotti2`
    FOREIGN KEY (`prodotti_id`)
    REFERENCES `beerify`.`prodotti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerify`.`metodi_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerify`.`metodi_pagamento` ;

CREATE TABLE IF NOT EXISTS `beerify`.`metodi_pagamento` (
  `id` INT NOT NULL,
  `metodo` VARCHAR(45) NULL,
  `codice_carta` VARCHAR(45) NULL,
  `data_scadenza` DATE NULL,
  `utenti_id` INT NOT NULL,
  PRIMARY KEY (`id`, `utenti_id`),
  INDEX `fk_metodi_pagamento_utenti1_idx` (`utenti_id` ASC),
  CONSTRAINT `fk_metodi_pagamento_utenti1`
    FOREIGN KEY (`utenti_id`)
    REFERENCES `beerify`.`utenti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerify`.`coupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beerify`.`coupon` ;

CREATE TABLE IF NOT EXISTS `beerify`.`coupon` (
  `id` INT NOT NULL,
  `cod` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
